# Data Preprocessing pipeline

Goal:
1. Aggregate the data
2. Clean the dataset
3. Prepare to store at vector store databse (pinecone)

## 1. Aggregate Data

In [1]:
import os
import pandas as pd

folder_path = "dataset/01_restaurant_scraped/"

df_list = []

for file_name in os.listdir(folder_path):
    # Step 1: filter CSV files
    if file_name.endswith(".csv"):
        # Step 2: build full path
        full_path = os.path.join(folder_path, file_name)
        
        # Step 3: read file
        df = pd.read_csv(full_path)
        
        # Optional MRT name
        mrt_name = file_name.replace(".csv", "")
        df["mrt_name"] = mrt_name
        
        df_list.append(df)

combined_df = pd.concat(df_list, ignore_index=True)

In [2]:
combined_df

,name,category,rating,reviews,price,address,status,snippet,img,url,postal,lon,lat,mrt_name
0,Yakiniku Like (The Clementi Mall),Yakiniku,4.7,"(1,666)",$10–20,"3155 Commonwealth Ave W, #05-35/36/37",Closed · Opens 11 am Sun,"""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Yakiniku+Lik...,129588.0,103.764725,1.314987,clementi
1,家羊地 - Jiayangdi - Bbq/烧烤 (Newest),Barbecue,4.7,(464),$20–30,"1 W Coast Dr, #01-97 NEWest",Open · Closes 2 am,"""Great",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/%E5%AE%B6%E7...,169655.0,103.827405,1.289417,clementi
2,Captain Kim Korean BBQ & Hotpot Buffet,Buffet,4.8,"(5,921)",$20–30,"3151 Commonwealth Ave W, #02-05 Grantral Mall ...",Closed · Opens 11:30 am Sun,"""Best experience ever , the",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Captain+Kim+...,529653.0,103.941943,1.352336,clementi
3,Ayer Rajah Food Centre,Hawker center,4.2,"(7,328)",$1–10,503 W Coast Dr,Open · Closes 1 am,"""The braised duck is delicious.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Ayer+Rajah+F...,120503.0,103.759751,1.311803,clementi
4,MEET Noodles 面面 Lanzhou Beef Noodle 兰州牛肉面,Self service restaurant,4.7,(928),$1–10,"3151 Commonwealth Ave W, #01-15 Grantral Mall ...",Closed · Opens 10:30 am Sun,"""Great",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/MEET+Noodles...,129581.0,103.765147,1.314270,clementi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12634,思carrot cake,Hawker Stall,NaN,NaN,NaN,"85 Redhill Ln, #01-56",Hawker Stall,NaN,https://streetviewpixels-pa.googleapis.com/v1/...,https://www.google.com/maps/place/%E6%80%9Dcar...,599213,103.775215,1.340788,redhill
12635,Western Delights,Hawker Stall,3.9,(8),$1–10,"85 Redhill Ln, #01-83",Closed · Opens 11:30 am Sun,"""The fish and chips so crispy yet the fish ins...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Western+Deli...,270020,103.788230,1.310997,redhill
12636,Ya Kun Kaya Toast (Artra),Cafe,3.5,(136),$1–10,"12 Alexandra View, #01-08",Closed · Opens 7:30 am Sun,"""Happy greeting to tasty",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Ya+Kun+Kaya+...,158745,103.817185,1.290031,redhill
12637,Redhill Katong Big Prawn Mee 红山加东大蝦麵,Hawker Stall,3.8,(33),$1–10,116 Bukit Merah Vw,Open 24 hours,"""He expertly cooked the prawn noodle soup and ...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/Redhill+Kato...,151116,103.821532,1.285134,redhill
12638,85 Redhill Teochew Fishball Noodle,Noodle Shop,2.6,(90),$1–10,"Vally Point Shopping Centre, 491 River Valley ...",Closed · Opens 8 am Sun,"""the curry had a little kick to it, and the po...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,https://www.google.com/maps/place/85+Redhill+T...,238839,103.845067,1.300821,redhill

## Save the data to aggregated folder

In [3]:
# Define the folder path and file name
folder_path = r'dataset/02_aggregated/'
file_name = 'aggregated_restaurant.csv'

# Create the directory if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Join the path and filename
final_path = os.path.join(folder_path, file_name)

# Save the DataFrame
combined_df.to_csv(final_path, index=False, encoding='utf-8')

## Data cleaning pipeline

Process:
- Remove entries if it has NaN  value in name, category, lat, or lon.
- Remove duplicate entries if it has the same url.
- Remoce duplicate name-address pairs

### Remove NaN values

In [4]:
initial_len = len(combined_df)
print(f"Initial rows: {initial_len}")

combined_df = combined_df.dropna(subset=["name", "category", "lat", "lon"])
print(f"After Nan Removal: {len(combined_df)}")

print(f'\nRemoved NaN entries: {initial_len - len(combined_df)} rows')

Initial rows: 12639
After Nan Removal: 12235

Removed NaN entries: 404 rows

### Remove duplicate URLs

In [5]:
initial_len = len(combined_df)
print(f"Initial rows: {initial_len}")

combined_df = (
    combined_df
    .groupby("url", as_index=False)
    .agg({"name": "first", "category": "first", "rating": "first", "reviews": "first", "price": "first", "address": "first", "status": "first", "snippet": "first", "img": "first", "postal": "first", "lon": "first", "lat": "first",
          "mrt_name": lambda x: list(x.dropna().unique())})
)

# Rename mrt column
combined_df = combined_df.rename(columns={"mrt_name": "nearest_mrt"})

print(f"After deduplication: {len(combined_df)}")
print(f"Removed rows: {initial_len - len(combined_df)}")

Initial rows: 12235
After deduplication: 8376
Removed rows: 3859

### Remove duplicate name-address pairs

In [6]:
initial_len = len(combined_df)
print(f"Initial rows: {initial_len}")

combined_df["name_norm"] = combined_df["name"].str.upper().str.strip()
combined_df["address_norm"] = combined_df["address"].str.upper().str.strip()

duplicates = combined_df[
    combined_df.duplicated(subset=["name_norm", "address_norm"], keep=False)
]

print("\n=== Duplicate (name, address) rows ===")
print(duplicates)

# drop duplicates
combined_df = combined_df.drop_duplicates(
    subset=["name_norm", "address_norm"],
    keep="first"
)

# Step 3: report results
final_len = len(combined_df)

print(f"\nAfter duplicate drop: {final_len}")
print(f"Removed duplicate rows: {initial_len - final_len}")

Initial rows: 8376

=== Duplicate (name, address) rows ===
                                                    url  \
8249  https://www.google.com/maps/place/Zaffron+Tand...
8250  https://www.google.com/maps/place/Zaffron+Tand...

                                                   name    category  rating  \
8249  Zaffron Tandoori - North Indian and Mexican Re...  Restaurant     4.8
8250  Zaffron Tandoori - North Indian and Mexican Re...  Restaurant     4.8

     reviews price       address                              status  \
8249   (240)  None  46 Boat Quay  Open · Closes 2 am · Reopens 11 am
8250   (240)  None  46 Boat Quay  Open · Closes 2 am · Reopens 11 am

            snippet                                                img  \
8249  "Outstanding   https://lh3.googleusercontent.com/gps-cs-s/AHV...
8250        Dine-in  https://lh3.googleusercontent.com/p/AF1QipPS1T...

       postal         lon       lat                       nearest_mrt  \
8249  49835.0  103.849376  1.286767  [bayfront, little_india, mattar]
8250    49835  103.849376  1.286767  [maxwell, great_world, downtown]

                                              name_norm  address_norm
8249  ZAFFRON TANDOORI - NORTH INDIAN AND MEXICAN RE...  46 BOAT QUAY
8250  ZAFFRON TANDOORI - NORTH INDIAN AND MEXICAN RE...  46 BOAT QUAY

After duplicate drop: 8375
Removed duplicate rows: 1

In [7]:
combined_df.head()

,url,name,category,rating,reviews,price,address,status,snippet,img,postal,lon,lat,nearest_mrt,name_norm,address_norm
0,https://www.google.com/maps/place/$1.50+Dim+Su...,$1.50 Dim Sum Bedok,Hawker Stall,3.7,(479),$1.50,"Block 123 Bedok North Street 2, 01-142",Open 24 hours,"""Very reasonable price n very delicious""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,460123.0,103.937343,1.329199,"[bedok_north, bedok_reservoir]",$1.50 DIM SUM BEDOK,"BLOCK 123 BEDOK NORTH STREET 2, 01-142"
1,https://www.google.com/maps/place/%2301-12+Han...,#01-12 Handmade Noodles,Hawker Stall,4.4,(12),$1–10,"4A Eunos Cres, #01-99 4A",Hawker Stall,"""It tastes not bad at all, extra crispy one si...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,402004,103.904256,1.320331,[eunos],#01-12 HANDMADE NOODLES,"4A EUNOS CRES, #01-99 4A"
2,https://www.google.com/maps/place/%2301-18+%E5...,#01-18 廣東砂煲飯。小吃,Hawker Stall,4.0,(5),$1–10,"#01-18 Geylang Bahru, Market & Food Centre",Hawker Stall,"""Very authentic and good claypot rice.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,330069.0,103.870005,1.321463,[geylang_bahru],#01-18 廣東砂煲飯。小吃,"#01-18 GEYLANG BAHRU, MARKET & FOOD CENTRE"
3,https://www.google.com/maps/place/%2301-20+%E8...,#01-20 萝卜糕 经济小吃,Hawker Stall,4.7,(11),$1–10,"22A Havelock Rd, #01-20",Closed · Opens 8 am,"""Fried till crispy yet not greasy.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,161022.0,103.829623,1.287971,[havelock],#01-20 萝卜糕 经济小吃,"22A HAVELOCK RD, #01-20"
4,https://www.google.com/maps/place/%2301-35+%E5...,#01-35 健康齋素食,Hawker Stall,5.0,(1),None,"79 Telok Blangah Dr, #01-35, Telok Blangah Foo...",Closed · Opens 6 am,Takeaway,NaN,100079.0,103.807618,1.273356,[telok_blangah],#01-35 健康齋素食,"79 TELOK BLANGAH DR, #01-35, TELOK BLANGAH FOO..."

### Remove or Map noisy categories

In [8]:
combined_df['category'].value_counts()

category
Hawker Stall                              1516
Restaurant                                1483
Chinese                                    593
Japanese                                   305
Indian                                     238
                                          ...
Soft drinks shop                             1
Takoyaki restaurant                          1
Educational institution                      1
Sweets and dessert buffet                    1
Unfussy rooms, plus a restaurant & bar       1
Name: count, Length: 295, dtype: int64

In [9]:
combined_df[combined_df['category'] == 'Educational institution']

,url,name,category,rating,reviews,price,address,status,snippet,img,postal,lon,lat,nearest_mrt,name_norm,address_norm
8242,https://www.google.com/maps/place/Yusof+Ishak+...,Yusof Ishak House,Educational institution,4.1,(64),None,31 Lower Kent Ridge Rd,Closed · Opens 9 am,"""They were excellent and delicious.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,119078.0,103.7748,1.298572,[kent_ridge],YUSOF ISHAK HOUSE,31 LOWER KENT RIDGE RD

In [10]:
import json

# normalize text
combined_df["category_clean"] = (combined_df["category"].astype(str).str.lower().str.strip())

with open("category_map.json", "r") as f:
    exact_map = json.load(f)

# Keyword rules
# keyword_rules = [
#     (["japanese", "sushi", "ramen", "takoyaki"], "japanese"),
#     (["chinese"], "chinese"),
#     (["indian"], "indian"),
#     (["hawker"], "local"),
#     (["cafe", "coffee"], "cafe"),
#     (["dessert", "sweet"], "dessert"),
# ]

# mapping function
def map_category(cat):
    cat = str(cat).lower()

    # check exact match
    if cat in exact_map:
        return exact_map[cat]

    # check keyword rules
    # for keywords, label in keyword_rules:
    #     for keyword in keywords:
    #         if keyword in cat:
    #             return label

    # fallback
    return cat

# apply mapping
combined_df["category_group"] = combined_df["category_clean"].apply(map_category)

# check results
pd.set_option("display.max_rows", None)
print(combined_df["category_group"].value_counts())

category_group
hawker                                    1661
restaurant                                1520
chinese                                    728
japanese                                   520
cafe                                       405
indian                                     315
fast_food                                  265
italian                                    200
thai                                       196
korean                                     193
halal                                      174
seafood                                    169
western                                    152
vegetarian                                 142
asian                                      107
food_court                                  77
bistro                                      72
mall                                        72
singaporean                                 70
taiwanese                                   65
vietnamese                                  60
bar                                         52
noodle shop                                 52
hot pot                                     46
steak                                       46
salad                                       45
mexican                                     42
dessert                                     39
french                                      39
chicken                                     29
indonesian                                  27
grill                                       26
nyonya restaurant                           26
sichuan                                     24
family-friendly                             23
buffet                                      23
yakiniku                                    22
barbecue                                    21
north indian                                17
turkish                                     17
bakery                                      15
hamburger                                   15
porridge restaurant                         14
transport                                   14
malaysian                                   14
steamboat restaurant                        13
asian fusion                                13
fine dining                                 13
mediterranean                               12
sandwich                                    11
railway services                            11
burmese                                     11
german                                      11
spanish                                     11
steamed bun shop                            10
gastropub                                   10
soup shop                                    9
chicken wings                                9
snack bar                                    8
greek                                        8
european                                     8
modern european                              8
hong kong style fast food restaurant         8
cha chaan teng (hong kong-style cafe)        7
açaí shop                                    7
park                                         7
modern french                                7
business center                              7
caterer                                      6
meat                                         6
dumpling                                     6
brunch                                       6
filipino                                     6
tonkatsu restaurant                          6
middle eastern                               5
corporate office                             5
french steakhouse restaurant                 5
community center                             5
transportation service                       5
poke bar                                     5
hotel                                        4
vegetarian cafe and deli                     4
market                                       4
diner                                        4
pancake                                      4
fish & chips                                 4
brewpub                                      4
soup                                         4
kebab shop                                   4
rice restaurant                              4
south east asian                             3
food and beverage consultant                 3
health food store                            3
japanese steakhouse                          3
cafeteria                                    3
garden                                       3
tourist attraction                           3
sports complex                               3
pakistani                                    3
food manufacturer                            3
tempura donburi restaurant                   3
condominium complex                          2
crab                                         2
persian                                      2
coffee store                                 2
lebanese                                     2
argentinian                                  2
tacos                                        2
juice                                        2
brazilian                                    2
social club                                  2
swiss                                        2
ayam penyet restaurant                       2
nasi restaurant                              2
kiosk                                        2
supermarket                                  2
mandarin restaurant                          2
syokudo and teishoku restaurant              2
karaoke bar                                  2
live music bar                               2
shop                                         2
soba noodle shop                             2
nepalese                                     2
event venue                                  2
kaiseki restaurant                           2
breakfast                                    2
oyster bar                                   2
japanese grocery store                       2
country club                                 2
soul                                         2
stadium                                      2
catering food and drink supplier             2
food products supplier                       2
pizza delivery                               2
·                                            2
gluten free                                  2
fried chicken                                2
wok restaurant                               1
bangladeshi                                  1
hakka                                        1
afghani                                      1
fish store                                   1
spanish restaurant                           1
arab restaurant                              1
temporarily closed                           1
european restaurant                          1
car repair and maintenance service           1
kosher                                       1
chocolate cafe                               1
bengali                                      1
vending machine supplier                     1
housing development                          1
peruvian                                     1
latin american                               1
outlet mall                                  1
small plates                                 1
coffee roastery                              1
cuban                                        1
community garden                             1
sporting goods store                         1
recreation center                            1
media company                                1
non-profit organization                      1
crêperie                                     1
performing arts theater                      1
closed                                       1
steak house                                  1
children's cafe                              1
fish restaurant                              1
dart bar                                     1
pempek restaurant                            1
corporate campus                             1
theme park                                   1
heritage museum                              1
relaxed hotel with a pool & dining           1
club                                         1
tea store                                    1
swedish                                      1
udon noodles                                 1
brasserie                                    1
mercantile development                       1
leisure center                               1
eastern european                             1
seafood wholesaler                           1
nature preserve                              1
war memorial                                 1
satay restaurant                             1
gourmet grocery store                        1
portuguese                                   1
trendy hotel with asian-fusion dining        1
japanized western restaurant                 1
high-end hotel with bay views & dining       1
ferry service                                1
kushiyaki restaurant                         1
modern hotel with an infinity pool           1
irish pub                                    1
delivery restaurant                          1
asian fusion restaurant                      1
golf club                                    1
tapas                                        1
live music                                   1
chic, modern hotel with a rooftop pool       1
sri lankan                                   1
barber shop                                  1
video karaoke                                1
marina                                       1
okonomiyaki restaurant                       1
russian                                      1
botanical garden                             1
convention center                            1
gift shop                                    1
sushi restaurant                             1
south asian                                  1
bar & grill                                  1
warehouse                                    1
golf course                                  1
cat cafe                                     1
holding company                              1
agricultural service                         1
oyster bar restaurant                        1
english                                      1
deli                                         1
vegan restaurant                             1
southern italian                             1
civic center                                 1
food manufacturing supply                    1
meat wholesaler                              1
soft drinks shop                             1
educational institution                      1
sweets and dessert buffet                    1
unfussy rooms, plus a restaurant & bar       1
Name: count, dtype: int64

In [11]:
pd.reset_option("display.max_rows")
combined_df

,url,name,category,rating,reviews,price,address,status,snippet,img,postal,lon,lat,nearest_mrt,name_norm,address_norm,category_clean,category_group
0,https://www.google.com/maps/place/$1.50+Dim+Su...,$1.50 Dim Sum Bedok,Hawker Stall,3.7,(479),$1.50,"Block 123 Bedok North Street 2, 01-142",Open 24 hours,"""Very reasonable price n very delicious""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,460123.0,103.937343,1.329199,"[bedok_north, bedok_reservoir]",$1.50 DIM SUM BEDOK,"BLOCK 123 BEDOK NORTH STREET 2, 01-142",hawker stall,hawker
1,https://www.google.com/maps/place/%2301-12+Han...,#01-12 Handmade Noodles,Hawker Stall,4.4,(12),$1–10,"4A Eunos Cres, #01-99 4A",Hawker Stall,"""It tastes not bad at all, extra crispy one si...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,402004,103.904256,1.320331,[eunos],#01-12 HANDMADE NOODLES,"4A EUNOS CRES, #01-99 4A",hawker stall,hawker
2,https://www.google.com/maps/place/%2301-18+%E5...,#01-18 廣東砂煲飯。小吃,Hawker Stall,4.0,(5),$1–10,"#01-18 Geylang Bahru, Market & Food Centre",Hawker Stall,"""Very authentic and good claypot rice.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,330069.0,103.870005,1.321463,[geylang_bahru],#01-18 廣東砂煲飯。小吃,"#01-18 GEYLANG BAHRU, MARKET & FOOD CENTRE",hawker stall,hawker
3,https://www.google.com/maps/place/%2301-20+%E8...,#01-20 萝卜糕 经济小吃,Hawker Stall,4.7,(11),$1–10,"22A Havelock Rd, #01-20",Closed · Opens 8 am,"""Fried till crispy yet not greasy.""",https://lh3.googleusercontent.com/gps-cs-s/AHV...,161022.0,103.829623,1.287971,[havelock],#01-20 萝卜糕 经济小吃,"22A HAVELOCK RD, #01-20",hawker stall,hawker
4,https://www.google.com/maps/place/%2301-35+%E5...,#01-35 健康齋素食,Hawker Stall,5.0,(1),None,"79 Telok Blangah Dr, #01-35, Telok Blangah Foo...",Closed · Opens 6 am,Takeaway,NaN,100079.0,103.807618,1.273356,[telok_blangah],#01-35 健康齋素食,"79 TELOK BLANGAH DR, #01-35, TELOK BLANGAH FOO...",hawker stall,hawker
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8371,https://www.google.com/maps/place/umisushi+Mou...,umisushi Mount Alvernia Hospital,Japanese,3.6,(59),$10–20,"820 Thomson Road, #01-27, Mount Alvernia Hospital",Closed · Opens 10 am Mon,"""Her warmth and attentiveness truly made my",https://lh3.googleusercontent.com/gps-cs-s/AHV...,574623,103.837774,1.341499,[caldecott],UMISUSHI MOUNT ALVERNIA HOSPITAL,"820 THOMSON ROAD, #01-27, MOUNT ALVERNIA HOSPITAL",japanese,japanese
8372,https://www.google.com/maps/place/umisushi+One...,umisushi One Raffles Place,Sushi takeaway,3.1,(87),$10–20,"1 Raffles Pl, #B1 - 24 / 25",Closed · Opens 10 am Mon,"""Good service, quality",https://lh3.googleusercontent.com/gps-cs-s/AHV...,48616,103.851073,1.284350,[raffles_place],UMISUSHI ONE RAFFLES PLACE,"1 RAFFLES PL, #B1 - 24 / 25",sushi takeaway,japanese
8373,https://www.google.com/maps/place/umisushi/dat...,umisushi,Japanese,3.7,(42),$1–10,"3 Simei Street 6, B1-K7 Eastpoint Mall",Closed · Opens 10 am Sun,"""Top-notch service, kind and friendly staff, a...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,278995.0,103.796399,1.312240,[simei],UMISUSHI,"3 SIMEI STREET 6, B1-K7 EASTPOINT MALL",japanese,japanese
8374,https://www.google.com/maps/place/waters+edge+...,waters edge Training Restaurant,Restaurant,3.2,(30),None,15 Woodlands Ave 9,Open 24 hours,"""It’s a training school for students joining t...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,738967.0,103.783018,1.445412,"[admiralty, woodlands]",WATERS EDGE TRAINING RESTAURANT,15 WOODLANDS AVE 9,restaurant,restaurant
8375,https://www.google.com/maps/place/zui+xian+lou...,zui xian lou restaurant,Restaurant,4.4,(34),$20–30,"62 Sungei Kadut Lp, #04-01",Temporarily closed,"""May be out of way but an ideal place for a go...",https://lh3.googleusercontent.com/gps-cs-s/AHV...,729507.0,103.742861,1.408160,[kranji],ZUI XIAN LOU RESTAURANT,"62 SUNGEI KADUT LP, #04-01",restaurant,restaurant

In [12]:
# Define the folder path and file name
folder_path = r'dataset/03_cleaned/'
file_name = 'cleaned_restaurant.csv'

# Create the directory if it doesn't exist
os.makedirs(folder_path, exist_ok=True)

# Join the path and filename
final_path = os.path.join(folder_path, file_name)

# Save the DataFrame
combined_df.to_csv(final_path, index=False, encoding='utf-8')